package com.android.memory.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.android.memory.bean._User;

import com.android.memory.bean._UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig _UserDaoConfig;

    private final _UserDao _UserDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        _UserDaoConfig = daoConfigMap.get(_UserDao.class).clone();
        _UserDaoConfig.initIdentityScope(type);

        _UserDao = new _UserDao(_UserDaoConfig, this);

        registerDao(_User.class, _UserDao);
    }
    
    public void clear() {
        _UserDaoConfig.getIdentityScope().clear();
    }

    public _UserDao get_UserDao() {
        return _UserDao;
    }

}
